review = "Review"
rate = "Rate"
length = "Length"
word_count = "WordCount"
classes_counts = {5: 9054, 4: 6039, 3: 2184, 2: 1793, 1: 1421}
min_class_samples = 1420
train_batch_size_per_class = 1200
svm_min_batch_size_per_class = 250
svm_test_size_per_class = int(svm_min_batch_size_per_class / 5)
letter = "Letter"
words = "Words"
sentences = "Sentences"
adjective = "Adjective"
comp_score = "CompoundScores"
pos_score = "PositivityScore"
neg_score = "NegativityScore"
neu_score = "NeutralityScore"
readability = "Readability"
